use_frameworks!

platform :ios, '10.0'

target 'QuicklySwift_Example' do
  pod 'QuicklySwift', :path => '../'
  pod 'RZColorfulSwift'
  
  target 'QuicklySwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
